services:
  swipy-django:
    image: "${WEB_IMAGE}"
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
      - ./staticfiles:/code/staticfiles
    env_file:
      - .env
    depends_on:
      - swipy-django-migration  # TODO oleksandr: depends_on does not wait for the container to exit

  swipy-django-migration:
    image: "${WEB_IMAGE}"
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
      - ./staticfiles:/code/staticfiles
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput

  swipy-nginx:
    image: nginx:1.22.1
    ports:
      # TODO oleksandr: do I need 0.0.0.0 here ?
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./swipy_link-chain.crt:/swipy/swipy_link-chain.crt
      - ./swipy_link.key:/swipy/swipy_link.key
    depends_on:
      - swipy-django
