services:
  swipy-django:
    image: "${WEB_IMAGE}"
    # TODO oleksandr: make sure to externalize sqlite using volumes (while you're still using sqlite)
    env_file:
      - .env

  swipy-nginx:
    image: nginx:1.22.1
    ports:
      # TODO oleksandr: do I need 0.0.0.0 here ?
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./swipy_link-chain.crt:/swipy/swipy_link-chain.crt
      - ./swipy_link.key:/swipy/swipy_link.key
    depends_on:
      - swipy-django
