services:
  swipy-django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env

  swipy-nginx:
    image: nginx:1.22.1
    ports:
      - "4433:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - swipy-django
