services:
  swipy-django:
    image: swipy-django-dev
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
      - ./staticfiles:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - swipy-django-migration

  swipy-django-migration:
    build: .
    image: swipy-django-dev
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
      - ./staticfiles:/code/staticfiles
