services:
  swipy_server:
    image: "${WEB_IMAGE}"
    env_file:
      - .env

  swipy_nginx:
    image: nginx:1.22.1
    ports:
      # TODO oleksandr: do I need 0.0.0.0 here ?
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - swipy_server
