services:
  swipy-django:
    build: .
    image: swipy-django-dev
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
      - ./staticfiles:/code/staticfiles
    env_file:
      - .env

  swipy-django-migration:
    image: swipy-django-dev
    env_file:
      - .env
    command: python manage.py collectstatic --noinput && python manage.py migrate --noinput
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
      - ./staticfiles:/code/staticfiles
    depends_on:
      - swipy-django
