# Generated by Django 4.1.6 on 2023-02-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramupdate",
            name="telegram_chat_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
