# Generated by Django 4.1.6 on 2023-02-09 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GptCompletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_timestamp_ms", models.BigIntegerField()),
                ("arrival_timestamp_ms", models.BigIntegerField()),
                ("chat_telegram_id", models.BigIntegerField(null=True)),
                ("prompt", models.TextField()),
                ("completion", models.TextField()),
                (
                    "triggering_update",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.telegramupdate"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="utterance",
            name="gpt_completion",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.gptcompletion"
            ),
        ),
    ]
