# Generated by Django 4.1.6 on 2023-02-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0002_gptcompletion_utterance_gpt_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptcompletion",
            name="temperature",
            field=models.FloatField(null=True),
        ),
    ]
