# Generated by Django 4.1.6 on 2023-02-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0002_telegramupdate_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramupdate",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
