# Generated by Django 4.1.6 on 2023-02-17 21:27

from django.db import migrations


def set_is_end_of_conv(apps, schema_editor):
    Utterance = apps.get_model("swipy_app", "Utterance")
    Utterance.objects.filter(text="/start", is_bot=True).update(is_end_of_conv=True)


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0005_utterance_is_end_of_conv"),
    ]

    operations = [
        migrations.RunPython(set_is_end_of_conv, migrations.RunPython.noop),
    ]
