# Generated by Django 4.1.6 on 2023-02-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0006_auto_20230217_2127"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_telegram_id", models.BigIntegerField()),
                ("last_update_timestamp_ms", models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="utterance",
            name="conversation",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.conversation"
            ),
        ),
    ]
