# Generated by Django 4.1.6 on 2023-02-18 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0007_conversation_utterance_conversation"),
    ]

    operations = []
