# Generated by Django 4.1.6 on 2023-02-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0008_auto_20230218_1930"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwipyUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_telegram_id", models.BigIntegerField()),
                ("first_name", models.TextField()),
                ("full_name", models.TextField()),
                (
                    "current_conversation",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.conversation"
                    ),
                ),
            ],
        ),
    ]
