# Generated by Django 4.1.6 on 2023-02-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0010_auto_20230219_1055"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="swipy_user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.swipyuser"),
        ),
    ]
