# Generated by Django 4.1.6 on 2023-02-19 11:27

from django.db import migrations


def populate_user_for_conversation(apps, schema_editor):
    Conversation = apps.get_model("swipy_app", "Conversation")
    SwipyUser = apps.get_model("swipy_app", "SwipyUser")
    for conversation in Conversation.objects.all():
        conversation.swipy_user = SwipyUser.objects.filter(chat_telegram_id=conversation.chat_telegram_id).first()
        conversation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0011_conversation_swipy_user"),
    ]

    operations = [
        migrations.RunPython(populate_user_for_conversation, migrations.RunPython.noop),
    ]
