# Generated by Django 4.1.6 on 2023-02-19 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0012_auto_20230219_1127"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="chat_telegram_id",
        ),
    ]
