# Generated by Django 4.1.6 on 2023-02-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0013_remove_conversation_chat_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptcompletion",
            name="swipy_user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.swipyuser"),
        ),
        migrations.AddField(
            model_name="telegramupdate",
            name="swipy_user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.swipyuser"),
        ),
        migrations.AddField(
            model_name="utterance",
            name="swipy_user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.swipyuser"),
        ),
    ]
