# Generated by Django 4.1.6 on 2023-02-19 11:49

from django.db import migrations


def populate_user_for_all_models(apps, schema_editor):
    TelegramUpdate = apps.get_model("swipy_app", "TelegramUpdate")
    Utterance = apps.get_model("swipy_app", "Utterance")
    GptCompletion = apps.get_model("swipy_app", "GptCompletion")
    SwipyUser = apps.get_model("swipy_app", "SwipyUser")
    for telegram_update in TelegramUpdate.objects.all():
        telegram_update.swipy_user = SwipyUser.objects.filter(
            chat_telegram_id=telegram_update.chat_telegram_id
        ).first()
        telegram_update.save()
    for utterance in Utterance.objects.all():
        utterance.swipy_user = SwipyUser.objects.filter(chat_telegram_id=utterance.chat_telegram_id).first()
        utterance.save()
    for gpt_completion in GptCompletion.objects.all():
        gpt_completion.swipy_user = SwipyUser.objects.filter(chat_telegram_id=gpt_completion.chat_telegram_id).first()
        gpt_completion.save()


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0014_gptcompletion_swipy_user_telegramupdate_swipy_user_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_user_for_all_models, migrations.RunPython.noop),
    ]
