# Generated by Django 4.1.6 on 2023-02-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0015_auto_20230219_1149"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gptcompletion",
            name="chat_telegram_id",
        ),
        migrations.RemoveField(
            model_name="telegramupdate",
            name="chat_telegram_id",
        ),
        migrations.RemoveField(
            model_name="utterance",
            name="chat_telegram_id",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="swipy_user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="swipy_app.swipyuser"),
        ),
        migrations.AlterField(
            model_name="gptcompletion",
            name="swipy_user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="swipy_app.swipyuser"),
        ),
        migrations.AlterField(
            model_name="swipyuser",
            name="chat_telegram_id",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="swipyuser",
            name="first_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="swipyuser",
            name="full_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="utterance",
            name="conversation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="swipy_app.conversation"),
        ),
        migrations.AlterField(
            model_name="utterance",
            name="swipy_user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="swipy_app.swipyuser"),
        ),
        migrations.AddIndex(
            model_name="utterance",
            index=models.Index(fields=["swipy_user", "arrival_timestamp_ms"], name="swipy_app_u_swipy_u_68d8bb_idx"),
        ),
    ]
