# Generated by Django 4.1.6 on 2023-02-19 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0016_remove_gptcompletion_chat_telegram_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utterance",
            name="is_end_of_conv",
        ),
    ]
