# Generated by Django 4.1.6 on 2023-02-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0017_gptcompletion_engine_gptcompletion_frequency_penalty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
