# Generated by Django 4.1.7 on 2023-02-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0019_auto_20230227_0649"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptcompletion",
            name="alternative_to_utterance",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.utterance"),
        ),
        migrations.AddField(
            model_name="gptcompletion",
            name="prompt_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
