# Generated by Django 4.1.7 on 2023-02-28 19:35

from django.db import migrations


def link_gpt_completion_as_alternative_to_utterance(apps, schema_editor):
    Utterance = apps.get_model("swipy_app", "Utterance")
    for utterance in Utterance.objects.all():
        if utterance.gpt_completion:
            utterance.gpt_completion.alternative_to_utterance = utterance
            utterance.gpt_completion.save(update_fields=["alternative_to_utterance"])


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0020_gptcompletion_alternative_to_utterance_and_more"),
    ]

    operations = [
        migrations.RunPython(link_gpt_completion_as_alternative_to_utterance, migrations.RunPython.noop),
    ]
