# Generated by Django 4.1.7 on 2023-03-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0021_auto_20230228_1935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gptcompletion",
            name="alternative_to_utterance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternative_completion_set",
                to="swipy_app.utterance",
            ),
        ),
    ]
