# Generated by Django 4.1.7 on 2023-03-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0022_alter_gptcompletion_alternative_to_utterance"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptcompletion",
            name="full_api_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
