# Generated by Django 4.1.7 on 2023-03-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0023_gptcompletion_full_api_response"),
    ]

    operations = [
        migrations.RenameField(
            model_name="utterance",
            old_name="conversation",
            new_name="conversation_obsolete",
        ),
    ]
