# Generated by Django 4.1.7 on 2023-03-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0024_rename_conversation_utterance_conversation_obsolete"),
    ]

    operations = [
        migrations.AddField(
            model_name="utterance",
            name="conversation_set",
            field=models.ManyToManyField(to="swipy_app.conversation"),
        ),
        migrations.AlterField(
            model_name="utterance",
            name="conversation_obsolete",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="utterance_set_obsolete",
                to="swipy_app.conversation",
            ),
        ),
    ]
