# Generated by Django 4.1.7 on 2023-03-07 19:39

from django.db import migrations


def copy_conversation_obsolete_to_conversation_set(apps, schema_editor):
    Utterance = apps.get_model("swipy_app", "Utterance")
    UtteranceConversation = apps.get_model("swipy_app", "UtteranceConversation")
    for utterance in Utterance.objects.all():
        if utterance.conversation_obsolete:
            UtteranceConversation.objects.create(
                utterance=utterance,
                conversation=utterance.conversation_obsolete,
                linked_timestamp_ms=utterance.arrival_timestamp_ms,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0025_alter_utterance_conversation_obsolete_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_conversation_obsolete_to_conversation_set, migrations.RunPython.noop),
    ]
