# Generated by Django 4.1.7 on 2023-03-07 19:06

from django.db import migrations


def copy_conversation_obsolete_to_conversation_set(apps, schema_editor):
    Utterance = apps.get_model("swipy_app", "Utterance")
    for utterance in Utterance.objects.all():
        if utterance.conversation_obsolete:
            utterance.conversation_set.add(utterance.conversation_obsolete)
        utterance.save(update_fields=["conversation_set"])


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0025_utterance_conversation_set_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_conversation_obsolete_to_conversation_set, migrations.RunPython.noop),
    ]
