# Generated by Django 4.1.7 on 2023-03-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0027_remove_utterance_conversation_obsolete"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptcompletion",
            name="alternative_to_utt_conv",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternative_gpt_completion_set",
                to="swipy_app.utteranceconversation",
            ),
        ),
    ]
