# Generated by Django 4.1.7 on 2023-03-08 14:41

from django.db import migrations


def copy_alt_to_utterance_to_alt_to_utt_conv(apps, schema_editor):
    GptCompletion = apps.get_model("swipy_app", "GptCompletion")
    for gpt_completion in GptCompletion.objects.all():
        if gpt_completion.alternative_to_utterance:
            gpt_completion.alternative_to_utt_conv = (
                gpt_completion.alternative_to_utterance.utteranceconversation_set.all()[0]
            )
            gpt_completion.save(update_fields=["alternative_to_utt_conv"])


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0028_gptcompletion_alternative_to_utt_conv"),
    ]

    operations = [
        migrations.RunPython(copy_alt_to_utterance_to_alt_to_utt_conv, migrations.RunPython.noop),
    ]
