# Generated by Django 4.1.7 on 2023-03-08 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0029_auto_20230308_1441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gptcompletion",
            name="alternative_to_utterance",
        ),
    ]
