# Generated by Django 4.1.7 on 2023-03-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0030_remove_gptcompletion_alternative_to_utterance"),
    ]

    operations = [
        migrations.AddField(
            model_name="utteranceconversation",
            name="gpt_completion",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="swipy_app.gptcompletion"
            ),
        ),
    ]
