# Generated by Django 4.1.7 on 2023-03-08 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0032_auto_20230308_1537"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utterance",
            name="gpt_completion",
        ),
    ]
