# Generated by Django 4.1.7 on 2023-03-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0033_remove_utterance_gpt_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="swipyuser",
            name="language_code",
            field=models.TextField(default="en"),
            preserve_default=False,
        ),
    ]
