# Generated by Django 4.1.7 on 2023-03-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swipy_app", "0034_swipyuser_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptcompletion",
            name="approx_token_number",
            field=models.IntegerField(null=True),
        ),
    ]
